name: sekai_news
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

  http: ^0.13.6
  google_fonts: ^4.0.4
  flutter_speed_dial: ^7.0.0
  flutter_cache_manager: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: false

  assets:
    - assets/

